### PR TITLE
Bump thresholds for `vw_pin_appeal` and `vw_pin_sale` tests that are failing

### PR DESCRIPTION
**Pull request by jeancochrane**
The sqoop bot is [currently failing](https://github.com/ccao-data/data-architecture/actions/runs/6221555617) due to two tests, one for `vw_pin_appeal` and one for `vw_pin_sale`, that are failing due to a few extra rows of invalid data.

This PR bumps the failure thresholds for those tests since we don't yet have a set process for fixing these errors.

### CODE REVIEW

**Review by dfsnow — APPROVED** [review]
Looking forward to putting these errors to bed permanently when I visit testing.

**Comment by wrridgeway** [comment]
> Looking forward to putting these errors to bed permanently when I visit testing.

Big talk.

**Comment by wrridgeway** [comment]
Okay, as we discussed briefly, @jeancochrane I'd change the threshold for `vw_pin_appeal_change_matches_appeal_outcome` to be a difference greater than 1 rather than just not equal.  I think it's mostly catching actually bad data outside of that, at least post-2020. Pre-2020 we're essentially still waiting for htpar to be properly updated with as400 data.

Other than that, I support whatever solution you and @dfsnow have decided on for how you want to address these tests throwing errors/warnings.

**Review by wrridgeway — APPROVED** [review]

**Comment by jeancochrane** [comment]
Good call @wrridgeway, I made that change in [b65f7e7](https://github.com/ccao-data/data-architecture/pull/139/commits/b65f7e7344291ffa439dd9799b92d09599cf0e3f)! Unfortunately it only seems to reduce the number of failing rows from 266,758 to 266,719 😕

**Comment by wrridgeway** [comment]
@jeancochrane looks good to me!

**Pull request merged**
