### PR TITLE
Add Chicago cbd boundary to `default.vw_pin_universe`

### PR DESCRIPTION
**Pull request by Damonamajor**
This adds a central business district boundary, which calculates a 1 for parcels in the district, and an empty value for those that are not.

### CODE REVIEW

**Comment by wrridgeway** [comment]
Let's lint the R scripts and run some tests to make sure
1) only parcels from chicago show up in the central business district
2) there are the same number of rose per year for `vw_pin_universe` as in the `default` athena database

**Comment by Damonamajor** [comment]
> 1. only parcels from chicago show up in the central business district

image


SELECT 
    census_acs5_place_geoid, 
    econ_central_business_district_num,
    COUNT(*) AS combination_count
FROM 
    "z_ci_368-add-chicago-cbd-boundary-to-pin-universe_default"."vw_pin_universe"
WHERE 
    econ_central_business_district_num = '1'
GROUP BY 
    census_acs5_place_geoid, 
    econ_central_business_district_num;

**Comment by Damonamajor** [comment]
> 2. there are the same number of rose per year for `vw_pin_universe` as in the `default` athena database

SELECT 
    a.year, 
    a.row_count AS row_count_a, 
    b.row_count AS row_count_b
FROM 
    (SELECT 
         year, 
         COUNT(*) AS row_count
     FROM 
         "z_ci_368-add-chicago-cbd-boundary-to-pin-universe_default"."vw_pin_universe"
     GROUP BY 
         year) a
JOIN 
    (SELECT 
         year, 
         COUNT(*) AS row_count
     FROM 
         "default"."vw_pin_universe"
     GROUP BY 
         year) b
ON 
    a.year = b.year;


image

**Review by wrridgeway — APPROVED** [review]
Looks good to me!

**Pull request merged**
