### PR TITLE
Remove deactivated iasWorld rows from Athena views

### PR DESCRIPTION
**Pull request by wrridgeway**
We discovered recently that several tables include `cur` and `deactivat` columns that should be invoked regularly; while ignoring these columns shouldn't lead to duplication, it will lead to old PINs that are no longer part of the universe being included in things like modelling and reporting.

This PR adds conditionals across the `default`, `modelling`, and `reporting` Athena DBs.

### CODE REVIEW

**Comment by wrridgeway** [comment]
Code is ready for review, but I need to spend a little time testing these changes on athena.

**Comment by wrridgeway** [comment]
After working through default, modeling, and reporting, the changes implemented in this PR appear to be working as expected.

**Comment by wrridgeway** [comment]
After working through default, modeling, and reporting, the changes implemented in this PR appear to be working as intended.

**Review by dfsnow — APPROVED** [review]
@wrridgeway, this looks set to go, pending double checking with Mirella.

**Pull request merged**
